CREATE TABLE "UCA"."AGREGAR_ARTICULO" 
   (	"CODIGOARTICULO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NOMBREARTICULO" VARCHAR2(50 BYTE), 
	"PRECIOCOSTO" NUMBER(*,0), 
	"PRECIOVENTA" NUMBER(*,0), 
	"ESTADO" VARCHAR2(10 BYTE), 
	 CONSTRAINT "PK_CODIGOARTICULO" PRIMARY KEY ("CODIGOARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE TABLE "UCA"."AGREGAR_PROVEEDOR" 
   (	"CODIGOPROVEEDOR" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NOMBREPROVEEDOR" VARCHAR2(50 BYTE), 
	"DIRECCIONPROVEEDOR" VARCHAR2(20 BYTE), 
	"DETALLE" VARCHAR2(30 BYTE), 
	"TELEFONO" NUMBER(10,0), 
	"CODIGOARTICULO" VARCHAR2(100 BYTE), 
	 CONSTRAINT "PK_NOMBREPROVEEDOR" PRIMARY KEY ("CODIGOPROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_CODIGOARTICULO" FOREIGN KEY ("CODIGOARTICULO")
	  REFERENCES "UCA"."AGREGAR_ARTICULO" ("CODIGOARTICULO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  CREATE TABLE "UCA"."INGRESAR_CLIENTE" 
   (	"NUMEROCEDULA" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"NOMBRECLIENTE" VARCHAR2(50 BYTE), 
	"PRIMERAPELLIDO" VARCHAR2(50 BYTE), 
	"SEGUNDOAPELLIDO" VARCHAR2(50 BYTE), 
	"TELEFONO" NUMBER(10,0), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"CORREO_ELECTRONICO" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_NUMEROCEDULA" PRIMARY KEY ("NUMEROCEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  
  CREATE TABLE "UCA"."INGRESAR_FACTURA" 
   (	"NUMEROFACTURA" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"NUMEROCEDULA" VARCHAR2(12 BYTE), 
	"NOMBRECLIENTE" VARCHAR2(50 BYTE), 
	"FECHA" DATE, 
	"TIPODECAMBIO" VARCHAR2(8 BYTE), 
	"CODIGODELPRODUCTO" VARCHAR2(1000 BYTE), 
	"NOMBREDELPRODUCTO" VARCHAR2(50 BYTE), 
	"CANTIDAD" VARCHAR2(100 BYTE), 
	"PRECIO" VARCHAR2(1000 BYTE), 
	"IMPORTE" VARCHAR2(1000 BYTE), 
	"SUBTOTAL" VARCHAR2(1000 BYTE), 
	"IMPUESTO" VARCHAR2(1000 BYTE), 
	 CONSTRAINT "PK_NUMEROFACTURA" PRIMARY KEY ("NUMEROFACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_NUMEROCEDULA" FOREIGN KEY ("NUMEROCEDULA")
	  REFERENCES "UCA"."INGRESAR_CLIENTE" ("NUMEROCEDULA") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "UCA"."FACTURA_TRIG" 
    BEFORE INSERT ON INGRESAR_FACTURA
        FOR EACH ROW
    BEGIN
        SELECT FACTURA_SECUENCIA.NEXTVAL 
        INTO :NEW.NUMEROFACTURA
        FROM DUAL;
    END;
/
ALTER TRIGGER "UCA"."FACTURA_TRIG" ENABLE;

  CREATE TABLE "UCA"."FACTURA" 
   (	"REFERENCIA" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"COD_CLIENTE" VARCHAR2(4 BYTE), 
	"COD_PAIS" VARCHAR2(5 BYTE), 
	"IMPORTE" NUMBER(10,2), 
	 CONSTRAINT "FACTURA_PK" PRIMARY KEY ("REFERENCIA", "COD_CLIENTE", "COD_PAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "UCA"."HACER_PEDIDOS" 
   (	"CODIGOPEDIDO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CODIGOARTICULO" VARCHAR2(100 BYTE), 
	"CODIGOPROVEEDOR" VARCHAR2(100 BYTE), 
	"CODIGOINVENTARIO" VARCHAR2(100 BYTE), 
	"FECHA" DATE, 
	"CANTIDAD" NUMBER(*,0), 
	"PUNTO_REORDEN" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PK_CODIGOPEDIDO" PRIMARY KEY ("CODIGOPEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;